export const GET_FLYERS = 'GET FLYERS';
export const FLYERS_LOADING = 'GET FLYERS LOADING';
export const FLYERS_FAILED = 'GET FLYERS FAILED';
export const GET_FAVORITES_FLYERS = 'GET FAVORITES FLYERS';
export const FLYERS_FAVORITES_LOADING = 'GET FAVORITES FLYERS LOADING';
export const FLYERS_FAVORITES_FAILED = 'GET FAVORITES FLYERS FAILED';
